import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    '2% fee per completed job': '2% fee per completed job',
    '24 hours charge': '24 hours charge',
    '48 hours charge': '48 hours charge',
    'A new job request has been assigned to you.': 'A new job request has been assigned to you.',
    'Admin has sent you a message.': 'Admin have sent u a message',
    'A user has sent you a message.': 'Admin have sent u a message',
    'A user requested your service': 'A user requested your service',
    'About': 'About',
    'About Us': 'About Us',
    'About DIP Services': 'About DIP Services',
    'Settings': 'Settings',
    'Appearance': 'Appearance',
    'Light': 'Light',
    'Dark': 'Dark',
    'Are you sure you want to delete this service?': 'Are you sure you want to delete this service?',
    'Bridging the gap between skill and need, right at your doorstep.': 'Bridging the gap between skill and need, right at your doorstep.',
    'Our Mission': 'Our Mission',
    'To empower local service providers and provide customers with seamless, reliable, and professional doorstep services through innovative technology.': 'To empower local service providers and provide customers with seamless, reliable, and professional doorstep services through innovative technology.',
    'Why DIP Services?': 'Why DIP Services?',
    'Verified Pros': 'Verified Pros',
    'Trusted and background-checked professionals.': 'Trusted and background-checked professionals.',
    'Instant Booking': 'Instant Booking',
    'Fast and easy scheduling at your fingertips.': 'Fast and easy scheduling at your fingertips.',
    'Quality Service': 'Quality Service',
    'Satisfaction guaranteed with premium standards.': 'Satisfaction guaranteed with premium standards.',
    'Local Impact': 'Local Impact',
    'Supporting local businesses and tradespeople.': 'Supporting local businesses and tradespeople.',
    'Wide Range of Services': 'Wide Range of Services',
    'Trade Services': 'Trade Services',
    'Plumbers, Electricians, Carpenters': 'Plumbers, Electricians, Carpenters',
    'Auto, Tempo, Catering, Halls': 'Auto, Tempo, Catering, Halls',
    'Community Support': 'Community Support',
    'Helping neighbors thrive': 'Helping neighbors thrive',
    'Know more about our mission': 'Know more about our mission',
    'Privacy Policy': 'Privacy Policy',
    'Terms of Service': 'Terms of Service',
    'Support & Info': 'Support & Info',
    'How we protect your data': 'How we protect your data',
    'Usage guidelines & rules': 'Usage guidelines & rules',
    'Version 2.4.0': 'Version 2.4.0',
    'Accept Job': 'Accept Job',
    'Accepted': 'Accepted',
    'Accepted Date': 'Accepted Date',
    'Action Required': 'Action Required',
    'Active': 'Active',
    'Address': 'Address',
    'Address / Locality': 'Address / Locality',
    'Admin': 'Admin',
    'Admin Console': 'Admin Console',
    'Advance': 'Advance',
    'All': 'All',
    'All Categories': 'All Categories',
    'All Orders': 'All Orders',
    'All Platform Orders': 'All Platform Orders',
    'All Users': 'All Users',
    'All Workers': 'All Workers',
    'Already have an account': 'Already have an account',
    'Amount': 'Amount',
    'Amount (High to Low)': 'Amount (High to Low)',
    'Amount (Low to High)': 'Amount (Low to High)',
    'App Settings': 'App Settings',
    'Auto': 'Auto',
    'Available': 'Worker Available',
    'Back to Stats': 'Back to Stats',
    'Base Rate': 'Base Rate',
    'Bio': 'Bio',
    'Blocked (Overdue)': 'Blocked (Overdue)',
    'Book': 'Book',
    'Book Service': 'Book Service',
    'Book Service Now': 'Book Service Now',
    'Booked': 'Booked',
    'Booking Accepted!': 'Booking Accepted!',
    'Booking Date': 'Booking Date',
    'Booking Declined': 'Booking Declined',
    'Booking Details': 'Booking Details',
    'Booking History': 'Booking History',
    'Booking Type': 'Booking Type',
    'Booking Update': 'Booking Update',
    'Booking advance': 'Booking advance',
    'Business Hours': 'Business Hours',
    'Business Stats': 'Business Stats',
    'Busy': 'Worker Busy',
    'By continuing, you agree to our Terms of Service and Privacy Policy.': 'By continuing, you agree to our Terms of Service and Privacy Policy.',
    'Call Now': 'Call Now',
    'Cancel Edit': 'Cancel Edit',
    'Cancel Order': 'Cancel Order',
    'Cancelling...': 'Cancelling...',
    'Cable': 'Cable',
    'Carpenter': 'Carpenter',
    'Catering': 'Catering',
    'Car': 'Car',
    'Charge per hour': 'Charge per hour',
    'Charge per kilometer': 'Charge per kilometer',
    'Chat': 'Chat',
    'Chat on WhatsApp': 'Chat on WhatsApp',
    'City': 'City',
    'City...': 'City...',
    'City:': 'City:',
    'Cleaner': 'Cleaner',
    'Client': 'Client',
    'Close': 'Close',
    'Closed': 'Closed',
    'Closing Time': 'Closing Time',
    'Coconut Plucker': 'Coconut Plucker',
    'Community Members': 'Community Members',
    'Complete Job': 'Complete Job',
    'Complete Your Profile': 'Complete Your Profile',
    'Completed': 'Completed',
    'Configure your outdoor service details': 'Configure your outdoor service details',
    'Configure your professional details': 'Configure your professional details',
    'Configure your shop details': 'Configure your shop details',
    'Confirm Completion': 'Confirm Completion',
    'Confirm Payment': 'Confirm Payment',
    'Confirming...': 'Confirming...',
    'Connect with other users in your area': 'Connect with other users in your area',
    'Contact & Address': 'Contact & Address',
    'Create Account': 'Create Account',
    'Create an account so you can explore all the existing services': 'Create an account so you can explore all the existing services',
    'Create new account': 'Create new account',
    'Customer': 'Customer',
    'DIP Services': 'DIP Services',
    'Daily Timings': 'Daily Timings',
    'Data stored successfully': 'Data stored successfully',
    'Date': 'Date',
    'Date Selection': 'Date Selection',
    'Days Remaining': 'Days Remaining',
    'Decline': 'Decline',
    'Declined': 'Declined',
    'Describe the Issue': 'Describe the Issue',
    'Description': 'Description',
    'Details': 'Details',
    'Discover Your': 'Discover Your',
    'Discover and connect with shops in your area': 'Discover and connect with shops in your area',
    'Doorstep Service Provider': 'Doorstep Service Provider',
    'Dream Service here': 'Dream Service here',
    'Due Today': 'Due Today',
    'Duration Selection': 'Duration Selection',
    'E.g. Broken pipe in bathroom...': 'E.g. Broken pipe in bathroom...',
    'Earnings': 'Earnings',
    'Edit': 'Edit',
    'Edit Details': 'Edit Details',
    'Edit Profile': 'Edit Profile',
    'Electrician': 'Electrician',
    'Email': 'Email',
    'Email Address': 'Email Address',
    'English': 'English',
    'Enter notification message...': 'Enter notification message...',
    'Enter notification title...': 'Enter notification title...',
    'Error booking worker.': 'Error booking worker.',
    'Error storing data': 'Error storing data',
    'Exp': 'Exp',
    'Experience': 'Experience',
    'Experience (High to Low)': 'Experience (High to Low)',
    'Experience (Low to High)': 'Experience (Low to High)',
    'Explore all the existing services based on your interest and needs': 'Explore all the existing services based on your interest and needs',
    'Fee:': 'Fee:',
    'Final Amount Received (₹)': 'Final Amount Received (₹)',
    'Finalize & Send Request': 'Finalize & Send Request',
    'Friday': 'Friday',
    'Full Day': 'Full Day',
    'Full Name': 'Full Name',
    'General Service': 'General Service',
    'Half Day': 'Half Day',
    'Hidden until accepted': 'Hidden until accepted',
    'Hire Services': 'Hire Services',
    'History Detail': 'History Detail',
    'House Rent': 'House Rent',
    'Shop Rent': 'Shop Rent',
    'I have paid the platform fee': 'I have paid the platform fee',
    'I want to': 'I want to',
    'Image Size': 'Image Size',
    'Job Completed': 'Job Completed',
    'Job Completed Successfully': 'Job Completed Successfully',
    'Job Declined': 'Job Declined',
    'Job Requests': 'Job Requests',
    'Job rejected successfully': 'Job rejected successfully',
    'Jobs': 'Jobs',
    'Jobs Completed': 'Jobs Completed',
    'Jobs Done': 'Jobs Done',
    'Joined': 'Joined',
    'Landmark': 'Landmark',
    'Landmark:': 'Landmark:',
    'Language': 'Language',
    'Loading Admin Data...': 'Loading Admin Data...',
    'Local Shops': 'Local Shops',
    'Login': 'Login',
    'Login here': 'Login here',
    'Logout': 'Logout',
    'Manage outdoor services': 'Manage outdoor services',
    'Manage your service bookings': 'Manage your service bookings',
    'Manage your shop': 'Manage your shop',
    'Manage your trade and rates': 'Manage your trade and rates',
    'Mark Completed': 'Mark Completed',
    'Mark Paid': 'Mark Paid',
    'JCB': 'JCB',
    'Marriage Hall': 'Marriage Hall',
    'Mason': 'Mason',
    'Mechanic': 'Mechanic',
    'Member since': 'Member since',
    'Members': 'Members',
    'Message': 'Message',
    'Messages': 'Messages',
    'Minimum charge': 'Minimum charge',
    'Monday': 'Monday',
    'Monthly Rent': 'Monthly Rent',
    'My Bookings': 'My Bookings',
    'My Services': 'My Services',
    'Near You': 'Near You',
    'Need to contact the worker again?': 'Need to contact the worker again?',
    'New Job Request': 'New Job Request',
    'New Job Request!': 'New Job Request!',
    'Message from Admin': 'Admin have sent u a message',
    'New Message': 'New Message',
    'New Message from Admin': 'Admin have sent u a message',
    'New Message from User': 'Admin have sent u a message',
    'Next Due:': 'Next Due:',
    'No': 'No',
    'No Bookings': 'No Bookings',
    'No History Found': 'No History Found',
    'No address provided': 'No address provided',
    'No community members found.': 'No community members found.',
    'No completed jobs yet': 'No completed jobs yet',
    'No description': 'No description',
    'No description provided.': 'No description provided.',
    'No hours set': 'No hours set',
    'No location': 'No location',
    'No orders found matching this filter.': 'No orders found matching this filter.',
    'No phone provided': 'No phone provided',
    'No shops found': 'No shops found',
    'No shops registered yet': 'No shops registered yet',
    'No weekly holidays': 'No weekly holidays',
    'No workers found in this category': 'No workers found in this category',
    'Notifications sent!': 'Notifications sent!',
    'Notify All': 'Notify All',
    'One Day Rate': 'One Day Rate',
    'One Time Rate': 'One Time Rate',
    'Open': 'Open',
    'Open Now': 'Open Now',
    'Opening Time': 'Opening Time',
    'Outdoor Service Profile': 'Outdoor Service Profile',
    'Outdoor Services': 'Outdoor Services',
    'Overdue': 'Overdue',
    'Owner': 'Owner',
    'Owner Name': 'Owner Name',
    'Paid': 'Paid',
    'Painter': 'Painter',
    'Password': 'Password',
    'Pay Now': 'Pay Now',
    'Pay via UPI': 'Pay via UPI',
    'Payment confirmation sent to admin for verification.': 'Payment confirmation sent to admin for verification.',
    'Payment verified successfully!': 'Payment verified successfully!',
    'Pending': 'Pending',
    'Pending Verifications': 'Pending Verifications',
    'Place of Work': 'Place of Work',
    'Enter work address...': 'Enter work address...',
    'Personal Details': 'Personal Details',
    'Phone Number': 'Phone Number',
    'Platform Commission': 'Platform Commission',
    'Platform Fee': 'Platform Fee',
    'Platform Fee:': 'Platform Fee:',
    'Platform Management': 'Platform Management',
    'Platform fee (2%)': 'Platform fee (2%)',
    'Please complete overdue jobs first.': 'Please complete overdue jobs first.',
    'Please fill in all fields': 'Please fill in all fields',
    'Plumber': 'Plumber',
    'Pre Booking (Advance)': 'Pre Booking (Advance)',
    'Pricing': 'Pricing',
    'Privacy & Security': 'Privacy & Security',
    'Processing...': 'Processing...',
    'Professional Bio': 'Professional Bio',
    'Profile': 'Profile',
    'Provide Services': 'Provide Services',
    'Quick Visit': 'Quick Visit',
    'Rate Now': 'Rate Now',
    'Rate Worker': 'Rate Worker',
    'Rate per Day': 'Rate per Day',
    'Rate per Hour': 'Rate per Hour',
    'Rate per KM': 'Rate per KM',
    'Rate per kilometer': 'Rate per kilometer',
    'Rated': 'Rated',
    'Recent Earnings': 'Recent Earnings',
    'Recent Orders': 'Recent Orders',
    'Recommended Workers': 'Recommended Workers',
    'Refresh Page': 'Refresh Page',
    'Register': 'Register',
    'Registered Workers': 'Registered Workers',
    'Rejected': 'Rejected',
    'Rejected Date': 'Rejected Date',
    'Rent per month': 'Rent per month',
    'Saturday': 'Saturday',
    'Save Changes': 'Save Changes',
    'Save Outdoor Profile': 'Save Outdoor Profile',
    'Save Service Profile': 'Save Service Profile',
    'Save Shop Profile': 'Save Shop Profile',
    'Saving...': 'Saving...',
    'Search by name or address...': 'Search by name or address...',
    'Search by name, city or number...': 'Search by name, city or number...',
    'Search shops, types, or locations...': 'Search shops, types, or locations...',
    'Search...': 'Search...',
    'Security deposit': 'Security deposit',
    'See All': 'See All',
    'Select Outdoor Service': 'Select Outdoor Service',
    'Select Your Trade': 'Select Your Trade',
    'Select a service': 'Select a service',
    'Select a trade': 'Select a trade',
    'Send Notification': 'Send Notification',
    'Service': 'Service',
    'Service Details': 'Service Details',
    'Service Profile': 'Service Profile',
    'Service Rates': 'Service Rates',
    'Services in': 'Services in',
    'Setup Outdoor Profile': 'Setup Outdoor Profile',
    'Setup Profile': 'Setup Profile',
    'Setup Service Profile': 'Setup Service Profile',
    'Setup Shop Profile': 'Setup Shop Profile',
    'Shop Name': 'Shop Name',
    'Shop Type': 'Shop Type',
    'Shops': 'Shops',
    'Sign In': 'Sign In',
    'Sign in': 'Sign in',
    'Sign up': 'Sign up',
    'Single meal service': 'Single meal service',
    'Sort By': 'Sort By',
    'Start a Conversation': 'Start a Conversation',
    'Starts from': 'Starts from',
    'Stats': 'Stats',
    'Sunday': 'Sunday',
    'Switch to User': 'Switch to User',
    'Switch to Worker': 'Switch to Worker',
    'TV Repair': 'TV Repair',
    'Tamil': 'Tamil',
    'Tap again to Confirm Cancel': 'Tap again to Confirm Cancel',
    'Tempo': 'Tempo',
    'The worker has accepted your job request.': 'The worker has accepted your job request.',
    'The worker is currently unavailable for this job.': 'The worker is currently unavailable for this job.',
    'There are no registered workers yet.': 'There are no registered workers yet.',
    'This fee will be added to your pending balance. You have 6 days to pay it.': 'This fee will be added to your pending balance. You have 6 days to pay it.',
    'This order has been cancelled by the user.': 'This order has been cancelled by the user.',
    'This order is no longer active or has been cancelled.': 'This order is no longer active or has been cancelled.',
    'Thursday': 'Thursday',
    'Tiles Worker': 'Tiles Worker',
    'Time': 'Time',
    'Time Selection': 'Time Selection',
    'Time not set': 'Time not set',
    'Title': 'Title',
    'To': 'To',
    'Total': 'Total',
    'Total Earnings': 'Total Earnings',
    'Total Orders': 'Total Orders',
    'Track your service requests': 'Track your service requests',
    'Try adjusting your search': 'Try adjusting your search',
    'Tuesday': 'Tuesday',
    'Two Day Rate': 'Two Day Rate',
    'Two Time Rate': 'Two Time Rate',
    'Two meals service': 'Two meals service',
    'Unknown': 'Unknown',
    'Unpaid Fee': 'Unpaid Fee',
    'Up to 1 hour': 'Up to 1 hour',
    'Up to 4 hours': 'Up to 4 hours',
    'Up to 8 hours': 'Up to 8 hours',
    'User': 'User',
    'User Details': 'User Details',
    'Users': 'Users',
    'Verified Worker': 'Verified Worker',
    'Verify': 'Verify',
    'Verify Payment': 'Verify Payment',
    'Verify Worker': 'Verify Worker',
    'Verifying...': 'Verifying...',
    'View All': 'View All',
    'View your bookings': 'View your bookings',
    'Wednesday': 'Wednesday',
    'Weekly': 'Weekly',
    'Weekly Holidays': 'Weekly Holidays',
    'Welcome': 'Welcome',
    'Welcome back you\'ve been missed!': "Welcome back you've been missed!",
    'Welder': 'Welder',
    'What do you need help with today?': 'What do you need help with today?',
    'WhatsApp': 'WhatsApp',
    'When you get new requests, they\'ll appear here.': "When you get new requests, they'll appear here.",
    'Worker': 'Worker',
    'Worker Details': 'Worker Details',
    'Worker Phone': 'Worker Phone',
    'Worker contact details are available in your WhatsApp history.': 'Worker contact details are available in your WhatsApp history.',
    'Workers': 'Workers',
    'Workers in': 'Workers in',
    'Working Hours': 'Working Hours',
    'You have a new message from Admin.': 'Admin have sent u a message',
    'You have a new message from User.': 'You have a new message from User.',
    'You have a new message from a user.': 'Admin have sent u a message',
    'You have overdue accepted jobs that are not marked as completed. Please complete them and pay the platform fee to accept new jobs.': 'You have overdue accepted jobs that are not marked as completed. Please complete them and pay the platform fee to accept new jobs.',
    'You have overdue platform fees. Please pay them in the Earnings section to accept new jobs.': 'You have overdue platform fees. Please pay them in the Earnings section to accept new jobs.',
    'You haven\'t booked any services yet.': "You haven't booked any services yet.",
    'You must be logged in to book a worker.': 'You must be logged in to book a worker.',
    'You need to set your trade and rates before you can receive job requests.': 'You need to set your trade and rates before you can receive job requests.',
    'Your Offer (₹)': 'Your Offer (₹)',
    'Your completed and rejected orders will appear here.': 'Your completed and rejected orders will appear here.',
    'Your job with the worker has been marked as completed.': 'Your job with the worker has been marked as completed.',
    'Your past service requests': 'Your past service requests',
    'accepted': 'accepted',
    'active': 'active',
    'all': 'all',
    'completed': 'completed',
    'declined': 'declined',
    'failed': 'failed',
    'pending': 'pending',
    'rejected': 'rejected',
    'success': 'success',
    'Total Revenue': 'Total Revenue',
    'Pending Verification': 'Pending Verification',
    'Worker Commission': 'Worker Commission',
    'User Cancellation Fee': 'User Cancellation Fee',
    'Total Users': 'Total Users',
    'Total Workers': 'Total Workers',
    'Confirm Verification': 'Confirm Verification',
    'Confirm Rejection': 'Confirm Rejection',
    'Are you sure you want to verify this payment? This will update the status permanently.': 'Are you sure you want to verify this payment? This will update the status permanently.',
    'Are you sure you want to reject this request? The user/worker will need to re-submit proof.': 'Are you sure you want to reject this request? The user/worker will need to re-submit proof.',
    'Yes, Verify': 'Yes, Verify',
    'Yes, Reject': 'Yes, Reject',
    'Stop': 'Stop',
    'Tamil Voice': 'Tamil Voice',
    'Listening...': 'Listening...',
    'Purpose of Travel': 'Purpose of Travel',
    'Travel Source to Destination': 'Travel Source to Destination',
    'E.g. Family trip to Chennai...': 'E.g. Family trip to Chennai...',
    'E.g. From Arumbakkam to T.Nagar...': 'E.g. From Arumbakkam to T.Nagar...',
    'Job Accepted': 'Job Taken / வேலை எடுக்கப்பட்டது',
    'This job has been accepted by another driver.': 'This job has been accepted by another driver / இந்த வேலை மற்றொரு ஓட்டுநரால் ஏற்றுக்கொள்ளப்பட்டது',
    'Search by name or trade...': 'Search by name or trade...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    localStorage.setItem('app_language', 'en');
  }, []);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
